### ISSUE TITLE
Unit convertions by AmbientSensorMessage

### ISSUE THREAD

**Issue by sillevl** [vives-projectwerk-2-2020/AmbiantSensorMessage#1]
The README.md file shows an example using the library. 

https://github.com/vives-projectwerk-2-2020/AmbiantSensorMessage/blob/cd3d41bf40614458d6ac7359f9d9b6557711de15/README.md#L26-L30

Sensor values should not be aware that they are converted (to fixed point notations) before being passed to the AmbientSensorMessage. In this way you can define the values using there true value representation. This results in the user of the library not needing to know the implementation or convertion algorithm that is used inside the library.

For example, temperature should be definded as a 23.45 float/double. It is te libraries responsibilitie to convert them to the format needed to transmit over LoRaWAN. ( divide by 100 )

The UML diagram needs to be updated as wel.

**Comment by sillevl** [comment]
Example change: 

```c++
#include "Simple-LoRaWAN.h"
#include "AmbiantSensorMessage.h"
#include "settings.h"

int main(void)
{
    float temperature = 22.64;  // value in °C
    float humidity = 9.55;      // value in %
    float pressure = 1013.5;    // value in hPa
    float pm25 = 12.3;          // value in µg/m³
    float pm10 = 23.4;          // value in µg/m³

    while(true) {
        SimpleLoRaWAN::Node node(keys, pins);
        ParticulaLora::AmbiantSensorMessage message;

        message.addTemperature(temperature);
        message.addHumidity(humidity);
        message.addPressure(pressure);
        message.addPM(pm25);
        message.addPM(pm10);

        node.send(message.getMessage(), message.getLength());
        wait(30.0);
    }

    return 0;
}

```

**Comment by maximva** [comment]
Thanks for the feedback, the argument types have been changed.
I also used your example values and comments to adjust the readme file.
